<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Services\IEmailService.cs~RF3e1b0dc6.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NETCore.MailKit" Version="2.1.0" />
  </ItemGroup>

</Project>
